// Why: keep the generated handler registrations separate from hook transport;
// both are independently sizeable and the installed extension concatenates them.
export function getPiAgentStatusHandlerSourceLines(): string[] {
  return [
    '// Why: pi assistant messages carry content as an array of parts',
    "// ({ type: 'text', text } / tool_use / tool_result / reasoning). We only",
    "// surface the concatenated text parts as the visible 'last assistant",
    "// message' for the dashboard preview — tool_use / reasoning would be",
    '// noise (the dashboard already shows the active tool name + input).',
    'function extractAssistantText(message: unknown): string {',
    "  if (!message || typeof message !== 'object') return ''",
    '  const content = (message as { content?: unknown }).content',
    "  if (typeof content === 'string') return content",
    "  if (!Array.isArray(content)) return ''",
    "  let out = ''",
    '  for (const part of content) {',
    "    if (part && typeof part === 'object' && (part as { type?: unknown }).type === 'text') {",
    '      const text = (part as { text?: unknown }).text',
    "      if (typeof text === 'string') out += text",
    '    }',
    '  }',
    '  return out',
    '}',
    '',
    "// Why: pi's tool_call event input shape is tool-specific (event.input is",
    '// the raw args object). The agent-hooks server already runs',
    '// deriveToolInputPreview(toolName, input) to render a friendly preview',
    "// for known tool names ('bash' → command, 'read'/'write'/'edit' → path,",
    '// etc.), so we forward the raw object verbatim under the same field',
    '// names Claude uses (tool_name / tool_input) and let the server pick the',
    '// preview. Keeps tool-name knowledge centralized on the receiver side.',
    '// Why: Pi runs each subagent as a child process that inherits the lead',
    "// pane's env, so a subagent agent_end would falsely notify the lead as",
    '// finished. The lead claims the pane by recording its pid; children see a',
    '// different pid and stay silent. Pid (not a boolean) because Pi re-invokes',
    '// this factory on in-process reload — a boolean reads as already-owned and',
    '// silences the lead itself. Nesting (not hasUI) so top-level `pi -p` reports.',
    'export default function (pi): void {',
    '  const ownerPid = process.env.ORCA_PI_STATUS_OWNED',
    '  const selfPid = String(process.pid)',
    '  const isNestedAgent = !!ownerPid && ownerPid !== selfPid',
    '  if (!ownerPid) process.env.ORCA_PI_STATUS_OWNED = selfPid',
    '  function reportsToPane(): boolean {',
    '    return !isNestedAgent',
    '  }',
    "  pi.on('before_agent_start', (event) => {",
    '    if (!reportsToPane()) return',
    "    post('before_agent_start', { prompt: event.prompt ?? '' })",
    '  })',
    '',
    "  pi.on('agent_start', () => {",
    '    if (!reportsToPane()) return',
    "    post('agent_start')",
    '  })',
    '',
    "  pi.on('tool_execution_start', (event) => {",
    '    if (!reportsToPane()) return',
    "    post('tool_execution_start', {",
    '      tool_name: event.toolName,',
    '      tool_input: event.args,',
    '    })',
    '  })',
    '',
    "  pi.on('tool_call', (event) => {",
    '    if (!reportsToPane()) return',
    "    post('tool_call', {",
    '      tool_name: event.toolName,',
    '      tool_input: event.input,',
    '    })',
    '  })',
    '',
    "  pi.on('tool_execution_end', (event) => {",
    '    if (!reportsToPane()) return',
    "    post('tool_execution_end', {",
    '      tool_name: event.toolName,',
    '    })',
    '  })',
    '',
    "  // Why: capture the assistant's final text on each completed message",
    '  // so the dashboard preview reflects the most recent reply even before',
    '  // agent_end fires. message_end is the right hook because pi guarantees',
    '  // it fires after the message is finalized (post-streaming).',
    "  pi.on('message_end', (event) => {",
    '    if (!reportsToPane()) return',
    "    if (event.message?.role !== 'assistant') return",
    '    const text = extractAssistantText(event.message)',
    '    if (!text) return',
    "    post('message_end', { role: 'assistant', text })",
    '  })',
    '',
    "  pi.on('agent_end', () => {",
    '    if (!reportsToPane()) return',
    "    post('agent_end')",
    '  })',
    '}',
    ''
  ]
}
